# 服务配置
host: "0.0.0.0"
port: 8080

# 数据库配置
database:
  driver: "mysql"
  dsn: "admin:admin@tcp(localhost:3306)/mianshiba?charset=utf8mb4&parseTime=True"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"

# Redis配置
redis:
  addr: "redis:6379"
  password: "${REDIS_PASSWORD}"
  db: 0
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_size: 10
  min_idle_conns: 5

# Hertz框架配置
hertz:
  log_level: "info"
  log_path: "./logs"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "60s"

# 安全性配置
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiration: "24h"
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Origin", "Content-Type", "Authorization"]
    expose_headers: []
    allow_credentials: true

openapi:
  # LLM 给用户的api-key加密密钥
  openapi_key_secret: "${OPENAPI_ENCRYPT_KEY}"
  # LLM api-key
  model_api_key: "${MODEL_OPENAI_API_KEY}"
  # LLM base-url
  model_base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  # LLM model
  model_model: "qwen-max"


minio:
  endpoint: "localhost:9000"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  bucket: "resume"
  use_ssl: false

# Kafka配置
kafka:
  brokers: "localhost:9092"
  resume_topic: "resume_parser"
  group_id: "mianshiba_consumer_group"
  timeout: "5s"
